---
# Ansible playbook for a Node.js API app server.
#
# @author Jeff Geerling (2015).

- hosts: all
  gather_facts: yes

  # vars_files:
  #   - vars/main.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
      become: yes

  # roles:
  #   - geerlingguy.firewall
  #   - geerlingguy.nodejs

  tasks:
  - name: Install node, npm, git
    apt: name={{item}} state=present
    with_items:
      - nodejs
      - npm
      - git
      - build-essential
    become: yes

  - name: Download DSP
    git:
      repo: https://github.com/giper45/DockerSecurityPlayground.git
      dest: /home/vagrant/DockerSecurityPlayground

  - name: Install npm packages
    npm: 
      path: /home/vagrant/DockerSecurityPlayground

  - name: Install forever node.js package globally.
    npm:
      name: forever
      global: yes
      state: present
    become: yes

  - name: "Check if DSP is running"
    command: forever list
    register: forever_list
    changed_when: false

  - name: "Start DSP."
    command: forever start /home/vagrant/DockerSecurityPlayground/index.js
    when: "forever_list.stdout.find('/home/vagrant/DockerSecurityPlayground/index.js') == -1"



    # - name: Ensure Node.js API app is present.
    #   git:
    #     repo: "{{ app_repository }}"
    #     version: "{{ app_version }}"
    #     dest: "{{ app_directory }}"
    #     accept_hostkey: true
    #   register: app_updated
    #   notify: restart forever apps

    # - name: Stop all running instances of the app.
    #   command: "forever stopall"
    #   when: app_updated.changed

    # - name: Ensure Node.js API app dependencies are present.
    #   npm: "path={{ app_directory }}"
    #   when: app_updated.changed

    # - name: Run Node.js API app tests.
    #   command: "npm test chdir={{ app_directory }}"
    #   when: app_updated.changed

    # - name: Get list of all running Node.js apps.
    #   command: forever list
    #   register: forever_list
    #   changed_when: false

    # - name: Ensure Node.js API app is started.
    #   command: "forever start {{ app_directory }}/app.js"
    #   when: "forever_list.stdout.find('app.js') == -1"

    # - name: Add cron entry to start Node.js API app on reboot.
    #   cron:
    #     name: "Start Node.js API app"
    #     special_time: reboot
    #     job: "forever start {{ app_directory }}/app.js"

  # handlers:
    # - name: restart forever apps
    #   command: "forever restartall"
